#!/bin/bash
# ==============================================================================
# File: /opt/Docker/Scripts/CompileAnimatedBanner.sh
# Purpose: Compiles the static ASCII banner and appends a safe, time-boxed 
#          spinning coin animation loop to the interactive login sequence.
# Security: 
#   - Enforces a strict iteration limit (1.6 seconds total run time) to 
#     prevent infinite TTY hangs during high CPU load.
#   - Implements SIGINT/SIGTERM traps to prevent terminal lockouts.
#   - Restores cursor visibility upon completion or abort.
# ==============================================================================

TARGET_SCRIPT="/etc/profile.d/MotdBanner.sh"
GLOBAL_BASHRC="/etc/bash.bashrc"

# ------------------------------------------------------------------------------
# Phase 1: Write the Execution Script Header
# ------------------------------------------------------------------------------
cat << 'SCRIPT_HEADER' > "$TARGET_SCRIPT"
#!/bin/bash
# WARNING: THIS FILE IS AUTO-GENERATED BY /opt/Docker/Scripts/CompileAnimatedBanner.sh. 
# DO NOT EDIT.

if [[ $- != *i* ]]; then
    return
fi

cat << 'MOTD_PAYLOAD'
SCRIPT_HEADER

# ------------------------------------------------------------------------------
# Phase 2: Compile the Static Gold Gradient Background
# ------------------------------------------------------------------------------
cat << 'EOF' | awk '
{
    len = length($0)
    center = 47
    for(i=1; i<=len; i++) {
        c = substr($0, i, 1)
        if(c == " ") {
            printf " "
        } else {
            dist = i - center
            if(dist < 0) dist = -dist
            
            if(dist <= 8) color = 226        
            else if(dist <= 16) color = 220  
            else if(dist <= 25) color = 214  
            else if(dist <= 35) color = 208  
            else color = 166                 
            
            printf "\033[38;5;%dm%s", color, c
        }
    }
    printf "\033[0m\n"
}' >> "$TARGET_SCRIPT"
                             #                                      #                              
                     .    ## #  +                                 #  # ##                          
                       ## ## ## #                                  # ## ## ##                      
                     #  #  #  #  .                                .#  #  # -#                      
                   #  # ## ## ##                                 .## ## ## #  #                    
                +# ## ## #- ##                                      ## ## ## #- #-                 
               #  # .# #  #                                            #  # #  #  #                
             #  #  # #  #            .      ##        ##                  #  # #  #  #             
           ## ## # ## #+            #####          #####                 ## ## # ## ##             
          #  # .# # ##            ##########          ####### #              ## # #. # -#          
         # ## # ## #            #### #######          ####### ####             # ## # ## #         
          ## # # ##            ###### #######          ##############   .        ## # # ##         
      #     # # #   .      +# ####### ######          ###### ####### #             # # #      .    
     ##                    ### ####### ######          ##### ####### ####                    ##-   
   #####   ## .         ####### ###### #####          ##### ###### #######            ##  #####    
   ###  ####           ######### ###########          #### ###### ########            ##### ###    
   ## #####           # ######### ##### ####          ########## ######### #            ##### .#   
   #  ####            ### ######### #########          ### ####- ########  ##              ####   # 
  ##                 ##### ######## #### #-          ####### +#######  #####                 + ##  
  ###   ##           ######## ####### ### ###          ##  ## #######  ########            -##  #### 
  ### ###           ########### ######. #####          ####  ###### -##########             #### ### 
  ## ####            ############ #### ######          ###### ###  #############             ### ### 
   # ##            ##    ########## # #######          ######## -##########  ##              ### #   
 #  .# .          ########.  +############## #######  ####### ######  ########             #  #  ## 
 ###  ###       . ##############    ######## # ###### ########   -##############            ##  #### 
 ## ####          ################ ########  #####  ######## ################             #### ### 
 ## ###             ############### ########  ####### ######## ##############              # ######  
  # ##  #         ##########-        ######## -      + #######    .+#########            ##  #  +# 
 ##    ##         ################## ######+######### ####### #################            ###    ## 
 #### ###          ########################-######### ###### ##################            #### #### 
 ### ####                                ####-   -+-- # #####                               #### ### 
  ## ####                                ########  ### ###                                   ######  
     ##  #                                   ####  ### #                                   #  ##     
  ##     ## .          .      +####        #--##  ## #        ######                   ##      ##  
  ##### +##             #####  #####      #####  ####       ##### ######               ### #####   
   ### ####                ##+ ###-   ##   ####-######    ###   #######                #### ####   
    ##  ###                 ################ +-####- ##########. -##+                  #### ##     
        ##  #  .             ###   #  ##### ###############   #   ####                 #  ##       
     #      ##                 ######  +##### #### #####  #####                    ##      #-      
      #### ###                ######   ###### ############    ######                #### #####     
      -### ### #                    ####### ###### #######                      ## ### ####        
       #### ## ###                  ####### ######## #######                   ##  ## ####         
     .         ####                   ############### ###                     #####                
         ####   #####.                                                       # ####   ####         
           ###### ## ###                                                 #### ## ######            
             #####   ##### .                                            #####   #####              
                   +# ########                                      ### ####  #        .           
                #######    #### .                                 # #####    ########              
                   #####    ##### ##.                        ### ##### #   ####                    
                      #######  ## ####                      #### ##  .######      .                
                        +######     ###                   ##-      .######                         
                             #########                    -#########                               
                               -########  ####     -####  ########.    .                           
                                          .#########                                               
                                       .###          ####                                          
EOF

# ------------------------------------------------------------------------------
# Phase 3: Append Static Warning Footers
# ------------------------------------------------------------------------------
printf "\033[38;5;196m\n" >> "$TARGET_SCRIPT"
cat << 'EOF' >> "$TARGET_SCRIPT"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ☣☣☠☣☣ ━┓
┃ PPPPPPPPPPPPPPPPP                                                                               ┃
┃ P::::::::::::::::P                                                                              ┃
┃ P::::::PPPPPP:::::P                                                                             ┃
┃ PP:::::P     P:::::P                                                                            ┃
┃  P::::P     P:::::Paaaaaaaaaaaaa  nnnn  nnnnnnnn        eeeeeeeeeeee        mmmmmmm    mmmmmmm  ┃
┃  P::::P     P:::::Pa::::::::::::a n:::nn::::::::nn    ee::::::::::::ee   mm:::::::m  m:::::::mm ┃
┃  P::::PPPPPP:::::P aaaaaaaaa:::::an::::::::::::::nn  e::::::eeeee:::::eem::::::::::mm::::::::::m┃
┃  P:::::::::::::PP           a::::ann:::::::::::::::ne::::::e     e:::::em::::::::::::::::::::::m┃
┃  P::::PPPPPPPPP      aaaaaaa:::::a  n:::::nnnn:::::ne:::::::eeeee::::::em:::::mmm::::::mmm:::::m┃
┃  P::::P            aa::::::::::::a  n::::n    n::::ne:::::::::::::::::e m::::m   m::::m   m::::m┃
┃  P::::P           a::::aaaa::::::a  n::::n    n::::ne::::::eeeeeeeeeee  m::::m   m::::m   m::::m┃
┃  P::::P          a::::a    a:::::a  n::::n    n::::ne:::::::e           m::::m   m::::m   m::::m┃
┃ PP::::::PP        a::::a    a:::::a  n::::n    n::::ne::::::::e          m::::m   m::::m   m::::m┃
┃ P::::::::P        a:::::aaaa::::::a  n::::n    n::::n e::::::::eeeeeeee  m::::m   m::::m   m::::m┃
┃ P::::::::P         a::::::::::aa:::a n::::n    n::::n  ee:::::::::::::e  m::::m   m::::m   m::::m┃
┃ PPPPPPPPPP          aaaaaaaaaa  aaaa nnnnnn    nnnnnn    eeeeeeeeeeeeee  mmmmmm   mmmmmm   mmmmmm┃
┃                                                                                                 ┃
┃                       S E C U R E   A I R - G A P P E D   F A C I L I T Y                       ┃
┃                       ALL ACTIONS ARE LOGGED. ALL DEVIATIONS ARE PUNISHED.                      ┃
┗━ ☣☣☠☣☣ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
EOF

printf "\033[38;5;255m\n" >> "$TARGET_SCRIPT"
cat << 'EOF' >> "$TARGET_SCRIPT"
.-.   .-..----..----.   .-. .----.     .--.     .----. .----. .-..-. .-..-..-.   .----..---. .----.
| |   | || {_  | {_     | |{ {__      / {} \    | {}  }| {}  }| || | | || || |   | {_ /   __}| {_  
| `--.| || |   | {__    | |.-._} }   /  /\  \   | .--' | .-. \| |\ \_/ /| || `--.| {__\  {_ }| {__ 
`----'`-'`-'   `----'   `-'`----'    `-'  `-'   `-'    `-' `-'`-' `---' `-'`----'`----'`---' `----'
 PROPERTY OF THE CAPITOL INFORMATION MINISTRY. YOUR PRESENCE IN THIS SYSTEM IS GRANTED, NOT OWNED.
EOF
printf "\033[0m\n" >> "$TARGET_SCRIPT"

# Close the Heredoc payload string
echo "MOTD_PAYLOAD" >> "$TARGET_SCRIPT"

# ------------------------------------------------------------------------------
# Phase 4: Inject the Time-Boxed Animation Loop
# ------------------------------------------------------------------------------
cat << 'ANIMATION_LOOP' >> "$TARGET_SCRIPT"

# SECURITY: Trap signals to safely abort animation and restore cursor visibility
trap 'tput cnorm; tput cud 2; return 2>/dev/null || exit' SIGINT SIGTERM
tput civis # Hide cursor

# Center the coin approximately 
printf "\n"

# Loop exactly 4 times (4 iterations * 4 frames * 0.1s = 1.6s total runtime)
for i in {1..4}; do
    # Frame 1 - Flat Target
    printf "\r\033[38;5;220m                                        ___                                       \n"
    printf "\r\033[38;5;220m                                      / ^ ^ \                                     \n"
    printf "\r\033[38;5;220m                                      \  V  /                                     \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 2 - Angled Spin
    printf "\r\033[38;5;214m                                        ___                                       \n"
    printf "\r\033[38;5;214m                                       / / /                                      \n"
    printf "\r\033[38;5;214m                                       \ \ \                                      \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 3 - Edge Matrix
    printf "\r\033[38;5;208m                                        ___                                       \n"
    printf "\r\033[38;5;208m                                        | |                                       \n"
    printf "\r\033[38;5;208m                                        | |                                       \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 4 - Returning Spin
    printf "\r\033[38;5;214m                                        ___                                       \n"
    printf "\r\033[38;5;214m                                       \ \ \                                      \n"
    printf "\r\033[38;5;214m                                       / / /                                      \033[0m"
    tput cuu 2; sleep 0.1
done

# Final State (Resting Coin)
printf "\r\033[38;5;226m                                        ___                                       \n"
printf "\r\033[38;5;226m                                      / ^ ^ \                                     \n"
printf "\r\033[38;5;226m                                      \  V  /                                     \033[0m"

# Push cursor securely below the animation block to prevent prompt overwriting
tput cud 2
printf "\n"

# SECURITY: Restore default terminal state
tput cnorm
trap - SIGINT SIGTERM
ANIMATION_LOOP

# Enforce secure execution permissions
chmod +x "$TARGET_SCRIPT"

# ------------------------------------------------------------------------------
# Phase 5: Docker Interactive Shell Patch
# ------------------------------------------------------------------------------
if grep -q "MotdBanner.sh" "$GLOBAL_BASHRC"; then
    echo "Docker hook exists."
else
    cat << 'HOOK_EOF' >> "$GLOBAL_BASHRC"

# Docker/Non-Login Shell Hook for MotdBanner
if [[ $- == *i* ]] && [[ -f /etc/profile.d/MotdBanner.sh ]] && [[ ! -o login ]]; then
    source /etc/profile.d/MotdBanner.sh
fi
HOOK_EOF
fi