#!/bin/bash
# ==============================================================================
# File: /opt/Docker/Scripts/CompileTheatricalBanner.sh
# Purpose: Compiles a theatrical, 5-second delayed, screen-clearing login sequence.
# Security: 
#   - Strictly encapsulates ASCII art in discrete Heredocs to prevent bash evaluation.
#   - Escapes backslashes in printf animation frames.
# ==============================================================================

TARGET_SCRIPT="/etc/profile.d/MotdBanner.sh"
GLOBAL_BASHRC="/etc/bash.bashrc"

# Wipe the target script clean before building
> "$TARGET_SCRIPT"

# ------------------------------------------------------------------------------
# Phase 1: Header and Initial Screen Purge
# ------------------------------------------------------------------------------
cat << 'EOF' >> "$TARGET_SCRIPT"
#!/bin/bash
# WARNING: THIS FILE IS AUTO-GENERATED BY /opt/Docker/Scripts/CompileTheatricalBanner.sh. DO NOT EDIT.

if [[ $- != *i* ]]; then return; fi
trap 'tput cnorm; tput clear; trap - SIGINT SIGTERM; return 2>/dev/null || exit' SIGINT SIGTERM
tput civis
tput clear

# Open the Logo block
cat << 'MOTD_LOGO'
EOF

# ------------------------------------------------------------------------------
# Phase 2: Render the Static Gold Gradient Logo
# ------------------------------------------------------------------------------
cat << 'RAW_LOGO' | awk '
{
    len = length($0)
    center = 47
    for(i=1; i<=len; i++) {
        c = substr($0, i, 1)
        if(c == " ") {
            printf " "
        } else {
            dist = i - center
            if(dist < 0) dist = -dist
            
            if(dist <= 8) color = 226        
            else if(dist <= 16) color = 220  
            else if(dist <= 25) color = 214  
            else if(dist <= 35) color = 208  
            else color = 166                 
            
            printf "\033[38;5;%dm%s", color, c
        }
    }
    printf "\033[0m\n"
}' >> "$TARGET_SCRIPT"
                             #                                      #                              
                     .    ## #  +                                 #  # ##                          
                       ## ## ## #                                  # ## ## ##                      
                     #  #  #  #  .                                .#  #  # -#                      
                   #  # ## ## ##                                 .## ## ## #  #                    
                +# ## ## #- ##                                      ## ## ## #- #-                 
               #  # .# #  #                                            #  # #  #  #                
             #  #  # #  #            .      ##        ##                  #  # #  #  #             
           ## ## # ## #+            #####          #####                 ## ## # ## ##             
          #  # .# # ##            ##########          ####### #              ## # #. # -#          
         # ## # ## #            #### #######          ####### ####             # ## # ## #         
          ## # # ##            ###### #######          ##############   .        ## # # ##         
      #     # # #   .      +# ####### ######          ###### ####### #             # # #      .    
     ##                    ### ####### ######          ##### ####### ####                    ##-   
   #####   ## .         ####### ###### #####          ##### ###### #######            ##  #####    
   ###  ####           ######### ###########          #### ###### ########            ##### ###    
   ## #####           # ######### ##### ####          ########## ######### #            ##### .#   
   #  ####            ### ######### #########          ### ####- ########  ##              ####   # 
  ##                 ##### ######## #### #-          ####### +#######  #####                 + ##  
  ###   ##           ######## ####### ### ###          ##  ## #######  ########            -##  #### 
  ### ###           ########### ######. #####          ####  ###### -##########             #### ### 
  ## ####            ############ #### ######          ###### ###  #############             ### ### 
   # ##            ##    ########## # #######          ######## -##########  ##              ### #   
 #  .# .          ########.  +############## #######  ####### ######  ########             #  #  ## 
 ###  ###       . ##############    ######## # ###### ########   -##############            ##  #### 
 ## ####          ################ ########  #####  ######## ################             #### ### 
 ## ###             ############### ########  ####### ######## ##############              # ######  
  # ##  #         ##########-        ######## -      + #######    .+#########            ##  #  +# 
 ##    ##         ################## ######+######### ####### #################            ###    ## 
 #### ###          ########################-######### ###### ##################            #### #### 
 ### ####                                ####-   -+-- # #####                               #### ### 
  ## ####                                ########  ### ###                                   ######  
     ##  #                                   ####  ### #                                   #  ##     
  ##     ## .          .      +####        #--##  ## #        ######                   ##      ##  
  ##### +##             #####  #####      #####  ####       ##### ######               ### #####   
   ### ####                ##+ ###-   ##   ####-######    ###   #######                #### ####   
    ##  ###                 ################ +-####- ##########. -##+                  #### ##     
        ##  #  .             ###   #  ##### ###############   #   ####                 #  ##       
     #      ##                 ######  +##### #### #####  #####                    ##      #-      
      #### ###                ######   ###### ############    ######                #### #####     
      -### ### #                    ####### ###### #######                      ## ### ####        
       #### ## ###                  ####### ######## #######                   ##  ## ####         
     .         ####                   ############### ###                     #####                
         ####   #####.                                                       # ####   ####         
           ###### ## ###                                                 #### ## ######            
             #####   ##### .                                            #####   #####              
                   +# ########                                      ### ####  #        .           
                #######    #### .                                 # #####    ########              
                   #####    ##### ##.                        ### ##### #   ####                    
                      #######  ## ####                      #### ##  .######      .                
                        +######     ###                   ##-      .######                         
                             #########                    -#########                               
                               -########  ####     -####  ########.    .                           
                                          .#########                                               
                                       .###          ####                                          
RAW_LOGO

# ------------------------------------------------------------------------------
# Phase 3: The 5-Second Animation Loop & Second Purge
# ------------------------------------------------------------------------------
cat << 'EOF' >> "$TARGET_SCRIPT"
MOTD_LOGO

printf "\n"

# 12 iterations * 4 frames * 0.1s = 4.8 seconds of execution time
for i in {1..12}; do
    # Frame 1 - Flat Target
    printf "\r\033[38;5;220m                                        ___                                       \n"
    printf "\r\033[38;5;220m                                      / ^ ^ \\                                     \n"
    printf "\r\033[38;5;220m                                      \\  V  /                                     \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 2 - Angled Spin
    printf "\r\033[38;5;214m                                        ___                                       \n"
    printf "\r\033[38;5;214m                                       / / /                                      \n"
    printf "\r\033[38;5;214m                                       \\ \\ \\                                      \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 3 - Edge Matrix
    printf "\r\033[38;5;208m                                        ___                                       \n"
    printf "\r\033[38;5;208m                                        | |                                       \n"
    printf "\r\033[38;5;208m                                        | |                                       \033[0m"
    tput cuu 2; sleep 0.1

    # Frame 4 - Returning Spin
    printf "\r\033[38;5;214m                                        ___                                       \n"
    printf "\r\033[38;5;214m                                       \\ \\ \\                                      \n"
    printf "\r\033[38;5;214m                                       / / /                                      \033[0m"
    tput cuu 2; sleep 0.1
done

# Final Resting Frame + 0.2s pause
printf "\r\033[38;5;226m                                        ___                                       \n"
printf "\r\033[38;5;226m                                      / ^ ^ \\                                     \n"
printf "\r\033[38;5;226m                                      \\  V  /                                     \033[0m"
sleep 0.2

# Purge the terminal buffer (Second Clear)
tput clear

# Print Warning Banner (Red)
echo -e '\033[38;5;196m'
cat << 'MOTD_WARNING'
EOF

# ------------------------------------------------------------------------------
# Phase 4: Append Static Warning Footers
# ------------------------------------------------------------------------------
cat << 'RAW_WARNING' >> "$TARGET_SCRIPT"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ☣☣☠☣☣ ━┓
┃ PPPPPPPPPPPPPPPPP                                                                               ┃
┃ P::::::::::::::::P                                                                              ┃
┃ P::::::PPPPPP:::::P                                                                             ┃
┃ PP:::::P     P:::::P                                                                            ┃
┃  P::::P     P:::::Paaaaaaaaaaaaa  nnnn  nnnnnnnn        eeeeeeeeeeee        mmmmmmm    mmmmmmm  ┃
┃  P::::P     P:::::Pa::::::::::::a n:::nn::::::::nn    ee::::::::::::ee   mm:::::::m  m:::::::mm ┃
┃  P::::PPPPPP:::::P aaaaaaaaa:::::an::::::::::::::nn  e::::::eeeee:::::eem::::::::::mm::::::::::m┃
┃  P:::::::::::::PP           a::::ann:::::::::::::::ne::::::e     e:::::em::::::::::::::::::::::m┃
┃  P::::PPPPPPPPP      aaaaaaa:::::a  n:::::nnnn:::::ne:::::::eeeee::::::em:::::mmm::::::mmm:::::m┃
┃  P::::P            aa::::::::::::a  n::::n    n::::ne:::::::::::::::::e m::::m   m::::m   m::::m┃
┃  P::::P           a::::aaaa::::::a  n::::n    n::::ne::::::eeeeeeeeeee  m::::m   m::::m   m::::m┃
┃  P::::P          a::::a    a:::::a  n::::n    n::::ne:::::::e           m::::m   m::::m   m::::m┃
┃ PP::::::PP        a::::a    a:::::a  n::::n    n::::ne::::::::e          m::::m   m::::m   m::::m┃
┃ P::::::::P        a:::::aaaa::::::a  n::::n    n::::n e::::::::eeeeeeee  m::::m   m::::m   m::::m┃
┃ P::::::::P         a::::::::::aa:::a n::::n    n::::n  ee:::::::::::::e  m::::m   m::::m   m::::m┃
┃ PPPPPPPPPP          aaaaaaaaaa  aaaa nnnnnn    nnnnnn    eeeeeeeeeeeeee  mmmmmm   mmmmmm   mmmmmm┃
┃                                                                                                 ┃
┃                       S E C U R E   A I R - G A P P E D   F A C I L I T Y                       ┃
┃                       ALL ACTIONS ARE LOGGED. ALL DEVIATIONS ARE PUNISHED.                      ┃
┗━ ☣☣☠☣☣ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
RAW_WARNING

cat << 'EOF' >> "$TARGET_SCRIPT"
MOTD_WARNING

# Print Footer (White)
echo -e '\033[38;5;255m'
cat << 'MOTD_FOOTER'
EOF

cat << 'RAW_FOOTER' >> "$TARGET_SCRIPT"
.-.   .-..----..----.   .-. .----.     .--.     .----. .----. .-..-. .-..-..-.   .----..---. .----.
| |   | || {_  | {_     | |{ {__      / {} \    | {}  }| {}  }| || | | || || |   | {_ /   __}| {_  
| `--.| || |   | {__    | |.-._} }   /  /\  \   | .--' | .-. \| |\ \_/ /| || `--.| {__\  {_ }| {__ 
`----'`-'`-'   `----'   `-'`----'    `-'  `-'   `-'    `-' `-'`-' `---' `-'`----'`----'`---' `----'
 PROPERTY OF THE CAPITOL INFORMATION MINISTRY. YOUR PRESENCE IN THIS SYSTEM IS GRANTED, NOT OWNED.
RAW_FOOTER

# ------------------------------------------------------------------------------
# Phase 5: Cleanup and Finalization
# ------------------------------------------------------------------------------
cat << 'EOF' >> "$TARGET_SCRIPT"
MOTD_FOOTER

# Reset coloring
echo -e '\033[0m'

# Restore the cursor visibility and release the emergency traps
tput cnorm
trap - SIGINT SIGTERM
EOF

# Enforce secure execution permissions
chmod +x "$TARGET_SCRIPT"

# ------------------------------------------------------------------------------
# Phase 6: Docker Interactive Shell Patch
# ------------------------------------------------------------------------------
if ! grep -q "MotdBanner.sh" "$GLOBAL_BASHRC"; then
    cat << 'HOOK_EOF' >> "$GLOBAL_BASHRC"

# Docker/Non-Login Shell Hook for MotdBanner
if [[ $- == *i* ]] && [[ -f /etc/profile.d/MotdBanner.sh ]] && [[ ! -o login ]]; then
    source /etc/profile.d/MotdBanner.sh
fi
HOOK_EOF
fi