#!/usr/bin/env bash

# STRICT MODE ENFORCEMENT
set -euo pipefail
IFS=$'\n\t'

# CONSTANTS
TARGET_USER_DIR="${HOME}"
TARGET_RC="${TARGET_USER_DIR}/.bashrc"
BACKUP_DIR="${TARGET_USER_DIR}/.bashrc_backups"

# Ensure we aren't running this as root to configure a standard user's shell
if [[ "${EUID}" -eq 0 && "${USER}" != "root" ]]; then
    echo "[!] FATAL: Do not run this via raw sudo to configure your personal shell. It will break ownership."
    exit 1
fi

echo "[*] Initiating .bashrc Hardening Protocol..."

# --- WIZARD: DATA COLLECTION ---
read -r -p "Enter session timeout in seconds (STIG demands 900 or less) [900]: " USER_TMOUT
USER_TMOUT=${USER_TMOUT:-900}
if ! [[ "$USER_TMOUT" =~ ^[0-9]+$ ]]; then
    echo "[!] FATAL: Invalid timeout value."
    exit 1
fi

read -r -p "Enter default umask (027 for group read, 077 for absolute isolation) [077]: " USER_UMASK
USER_UMASK=${USER_UMASK:-077}
if ! [[ "$USER_UMASK" =~ ^[0-7]{3}$ ]]; then
    echo "[!] FATAL: Invalid umask."
    exit 1
fi

# --- ATOMIC BACKUP ---
mkdir -p "${BACKUP_DIR}"
chmod 700 "${BACKUP_DIR}"

if [[ -f "${TARGET_RC}" ]]; then
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="${BACKUP_DIR}/bashrc_backup_${TIMESTAMP}"
    echo "[*] Creating atomic backup at ${BACKUP_FILE}..."
    cp -a "${TARGET_RC}" "${BACKUP_FILE}"
    chmod 600 "${BACKUP_FILE}"
fi

# --- CLEAN ROOM: CONFIGURATION GENERATION ---
# Create a temporary file that only we can read/write
TMP_RC=$(mktemp /tmp/bashrc_staged.XXXXXX)
chmod 600 "${TMP_RC}"

# Trap ensures we destroy the temporary file if the script dies before the atomic swap
trap 'rm -f "${TMP_RC}"; echo "[!] Script interrupted. Cleared temporary staging file."' EXIT

echo "[*] Forging new configuration..."

cat << 'EOF' > "${TMP_RC}"
# =========================================================================
# HARDENED .bashrc - AUTOGENERATED
# Any manual modifications to this file may be overwritten by the auditor.
# =========================================================================

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

EOF

# Append our hardened configurations dynamically
cat << EOF >> "${TMP_RC}"
# --- DISA STIG / HARDENING SETTINGS ---

# 1. Enforce umask (File creation privacy)
umask ${USER_UMASK}

# 2. Prevent core dumps (No memory secrets written to disk)
ulimit -c 0

# 3. Session Timeout (Kill inactive shells)
# Declared readonly so the user cannot simply 'unset TMOUT'
TMOUT=${USER_TMOUT}
readonly TMOUT
export TMOUT

# 4. History Configuration
# Increase history size, timestamp everything, ignore duplicates
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%F %T "
# Append to the history file, don't overwrite it
shopt -s histappend

# --- ALIAS PROTECTIONS ---
# Defensive aliases to prevent catastrophic typos
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# --- DEFAULT PARROT/DEBIAN PATH SANITIZATION ---
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

EOF

echo "[*] Hardened configuration written to temporary enclave."

# --- THE ATOMIC SWAP ---
echo "[*] Executing atomic replacement..."
mv "${TMP_RC}" "${TARGET_RC}"

# Remove the trap since the swap succeeded
trap - EXIT

# Ensure final permissions are absolute
chmod 640 "${TARGET_RC}"
chown "${USER}":"$(id -gn "${USER}")" "${TARGET_RC}"

echo "[+] Operation complete. The execution vector is secured."
echo "    Run 'source ~/.bashrc' or spawn a new shell to enforce the new reality."