#!/usr/bin/env bash

# STRICT MODE ENFORCEMENT
set -euo pipefail
IFS=$'\n\t'

# CONSTANTS
TARGET_USER_DIR="${HOME}"
TARGET_RC="${TARGET_USER_DIR}/.bashrc"
BACKUP_DIR="${TARGET_USER_DIR}/.bashrc_backups"

# Enforce User Space
if [[ "${EUID}" -eq 0 && "${USER}" != "root" ]]; then
    echo "[!] FATAL: Running this via raw sudo shatters ownership. Aborting."
    exit 1
fi

# Dependency Validation
if ! command -v gum >/dev/null 2>&1; then
    echo "[!] FATAL: 'gum' binary not found in PATH."
    echo "    I will not compromise the air-gap to fetch it for you. Provision it securely and retry."
    exit 1
fi

gum style --border double --margin "1" --padding "1" --border-foreground 212 "Initiating STIG-Compliant .bashrc Hardening Protocol"

# --- WIZARD: AESTHETIC DATA COLLECTION ---

# Timeout Collection & Validation
gum style "Select Session Timeout (STIG demands <= 900 seconds)"
USER_TMOUT=$(gum input --placeholder "900" --prompt "Seconds > " --width 20)
USER_TMOUT=${USER_TMOUT:-900}

if ! [[ "${USER_TMOUT}" =~ ^[0-9]+$ ]] || [[ "${USER_TMOUT}" -gt 900 ]]; then
    gum style --foreground 196 "[!] FATAL: Invalid or non-compliant timeout. Discarding input."
    exit 1
fi

# Umask Collection & Validation
gum style "Select Default Umask Level"
UMASK_CHOICE=$(gum choose "077 (Paranoid - Absolute Isolation)" "027 (Group Read - STIG Minimum)")

if [[ "${UMASK_CHOICE}" == *"077"* ]]; then
    USER_UMASK="077"
elif [[ "${UMASK_CHOICE}" == *"027"* ]]; then
    USER_UMASK="027"
else
    gum style --foreground 196 "[!] FATAL: Unknown umask selection."
    exit 1
fi

# Final Confirmation before touching the filesystem
gum style "Configuration Ready. Target: ${TARGET_RC} | Umask: ${USER_UMASK} | Timeout: ${USER_TMOUT}"
if ! gum confirm "Execute Atomic Swap?"; then
    gum style --foreground 214 "[*] Operation aborted by user. The filesystem remains untouched."
    exit 0
fi

# --- ATOMIC BACKUP ---
mkdir -p "${BACKUP_DIR}"
chmod 700 "${BACKUP_DIR}"

if [[ -f "${TARGET_RC}" ]]; then
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="${BACKUP_DIR}/bashrc_backup_${TIMESTAMP}"
    cp -a "${TARGET_RC}" "${BACKUP_FILE}"
    chmod 600 "${BACKUP_FILE}"
    gum style --foreground 70 "[*] Atomic backup created at: ${BACKUP_FILE}"
fi

# --- CLEAN ROOM: CONFIGURATION GENERATION ---
TMP_RC=$(mktemp /tmp/bashrc_staged.XXXXXX)
chmod 600 "${TMP_RC}"

# Trap ensures temporary file destruction upon sudden termination
trap 'rm -f "${TMP_RC}"; echo "[!] Script interrupted. Cleared temporary staging file."' EXIT

cat << 'EOF' > "${TMP_RC}"
# =========================================================================
# HARDENED .bashrc - AUTOGENERATED
# Any manual modifications to this file may be overwritten by the auditor.
# =========================================================================

case $- in
    *i*) ;;
      *) return;;
esac

EOF

# Inject sanitized variables
cat << EOF >> "${TMP_RC}"
# --- DISA STIG / HARDENING SETTINGS ---
umask ${USER_UMASK}
ulimit -c 0

TMOUT=${USER_TMOUT}
readonly TMOUT
export TMOUT

HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%F %T "
shopt -s histappend

# --- ALIAS PROTECTIONS ---
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# --- DEFAULT PATH SANITIZATION ---
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

EOF

# --- THE ATOMIC SWAP ---
mv "${TMP_RC}" "${TARGET_RC}"

# Disarm the trap; the swap succeeded
trap - EXIT

# Lock permissions down
chmod 640 "${TARGET_RC}"
chown "${USER}":"$(id -gn "${USER}")" "${TARGET_RC}"

gum style --foreground 70 --border normal --padding "1" "Operation complete. The execution vector is secured. Spawn a new shell to enforce the new reality."